# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-19 16:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance', models.PositiveIntegerField(blank=True)),
                ('balance', models.PositiveIntegerField(blank=True)),
                ('discount', models.PositiveIntegerField(blank=True, default=0)),
                ('paidamount', models.PositiveIntegerField(blank=True)),
                ('credit_to_sp_id', models.PositiveIntegerField(blank=True, default=0)),
                ('credit_to_Self', models.PositiveIntegerField(blank=True)),
                ('dateof_Transaction', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_serviceprovider', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servicebooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofservicereq', models.CharField(max_length=100)),
                ('fromdate', models.DateField(default=datetime.date.today)),
                ('todate', models.DateField(blank=True)),
                ('sp_id', models.PositiveIntegerField(blank=True, default=0)),
                ('sp_name', models.CharField(max_length=50, verbose_name='Service Provider')),
                ('servicecharge', models.PositiveIntegerField()),
                ('bookingdate', models.DateField(auto_now=True)),
                ('total_days', models.PositiveIntegerField()),
                ('total_amount', models.PositiveIntegerField(blank=True)),
                ('sbapproval', models.CharField(blank=True, choices=[('Not_Approved', 'Not Approved'), ('Approved', 'Approved'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=20)),
                ('feedback', models.TextField(blank=True, max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='serviceprovider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spname', models.CharField(max_length=50, verbose_name='Service Provider')),
                ('contact', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('group_type', models.CharField(choices=[('Group', 'Group of People'), ('Individual', 'Individual')], max_length=20)),
                ('sp_type', models.CharField(max_length=100, verbose_name='Type of Service')),
                ('address', models.TextField(max_length=200)),
                ('from_time', models.TimeField(blank=True)),
                ('to_time', models.TimeField(blank=True)),
                ('twenty_four_hrs', models.BooleanField(default=False)),
                ('service_charge', models.PositiveIntegerField()),
                ('verification_status', models.CharField(max_length=100)),
                ('active_status', models.CharField(choices=[('A', 'Active'), ('I', 'In active')], max_length=1)),
                ('created_date', models.DateField(auto_now=True)),
                ('spid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='sbid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Servicebooking'),
        ),
    ]
