# Generated by Django 4.2.30 on 2026-05-29 16:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceprovider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spname', models.CharField(max_length=50, verbose_name='Service Provider')),
                ('contact', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('group_type', models.CharField(choices=[('Individual', 'Individual'), ('Group', 'Group of People')], max_length=20)),
                ('sp_type', models.CharField(max_length=100, verbose_name='Type of Service')),
                ('experience', models.CharField(blank=True, max_length=100, null=True, verbose_name='Experience details')),
                ('specialization', models.TextField(blank=True, max_length=100, null=True, verbose_name='Specialization')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('address', models.TextField(max_length=200)),
                ('from_time', models.TimeField(blank=True)),
                ('to_time', models.TimeField(blank=True)),
                ('twenty_four_hrs', models.BooleanField(default=False)),
                ('service_charge', models.PositiveIntegerField()),
                ('verification_status', models.CharField(blank=True, max_length=100, null=True)),
                ('active_status', models.CharField(choices=[('Active', 'Active'), ('In Active', 'In active')], default='Active', max_length=20)),
                ('created_date', models.DateField(auto_now=True)),
                ('spid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servicebooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofservicereq', models.CharField(max_length=100)),
                ('fromdate', models.DateField(default=datetime.date.today)),
                ('todate', models.DateField(blank=True, null=True)),
                ('sp_id', models.PositiveIntegerField(blank=True, default=0)),
                ('sp_name', models.CharField(max_length=50, verbose_name='Service Provider')),
                ('servicecharge', models.PositiveIntegerField()),
                ('bookingdate', models.DateField(auto_now=True)),
                ('total_days', models.PositiveIntegerField(blank=True, default=0)),
                ('total_amount', models.PositiveIntegerField(blank=True, default=0)),
                ('sbapproval', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Not Approved', max_length=20)),
                ('address_remarks', models.TextField(blank=True, max_length=200)),
                ('feedback', models.TextField(blank=True, max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=12)),
                ('is_serviceprovider', models.BooleanField(blank=True, default=False)),
                ('is_customer', models.BooleanField(blank=True, default=False)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance', models.PositiveIntegerField(blank=True, default=0)),
                ('balance', models.PositiveIntegerField(blank=True, default=0)),
                ('discount', models.PositiveIntegerField(blank=True, default=0)),
                ('paidamount', models.PositiveIntegerField(blank=True, default=0)),
                ('credit_to_sp_id', models.PositiveIntegerField(blank=True, default=0)),
                ('credit_to_Self', models.PositiveIntegerField(blank=True, default=0)),
                ('dateof_Transaction', models.DateField(default=datetime.date.today)),
                ('sbid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.servicebooking')),
            ],
        ),
    ]
