# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-21 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='remarks',
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='address_remarks',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='sbapproval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Not_Approved', 'Not Approved'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='active_status',
            field=models.CharField(choices=[('I', 'In active'), ('A', 'Active')], max_length=1),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='group_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Group', 'Group of People')], max_length=20),
        ),
    ]
