# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-22 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200121_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='advance',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='balance',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='credit_to_Self',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paidamount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='sbapproval',
            field=models.CharField(blank=True, choices=[('Not_Approved', 'Not Approved'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='todate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='total_days',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='active_status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'In active')], max_length=1),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='group_type',
            field=models.CharField(choices=[('Group', 'Group of People'), ('Individual', 'Individual')], max_length=20),
        ),
    ]
