# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-25 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200122_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='sbapproval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Not Approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='active_status',
            field=models.CharField(choices=[('In Active', 'In active'), ('Active', 'Active')], default='Active', max_length=1),
        ),
    ]
