# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-20 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200225_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Experience details'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Experience details'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='sbapproval',
            field=models.CharField(blank=True, choices=[('Not Approved', 'Not Approved'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved')], default='Not Approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='group_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Group', 'Group of People')], max_length=20),
        ),
    ]
