# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-21 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200420_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='sbapproval',
            field=models.CharField(blank=True, choices=[('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Not Approved', 'Not Approved'), ('Approved', 'Approved')], default='Not Approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='active_status',
            field=models.CharField(choices=[('In Active', 'In active'), ('Active', 'Active')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='group_type',
            field=models.CharField(choices=[('Group', 'Group of People'), ('Individual', 'Individual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='specialization',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Specialization'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='verification_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
