# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2024-06-30 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200421_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='sbapproval',
            field=models.CharField(blank=True, choices=[('Not Approved', 'Not Approved'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved')], default='Not Approved', max_length=20),
        ),
    ]
