# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-05-22 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20240630_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='sbapproval',
            field=models.CharField(blank=True, choices=[('Not Approved', 'Not Approved'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='Not Approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='active_status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Active', 'In active')], default='Active', max_length=20),
        ),
    ]
